version: '3.8'

services:
  db:
    image: postgres:16.0-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "$DEV_HOST:$FRONT_PORT"
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"

  api:
    build: .
    volumes:
      - ./:/app
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - db
    ports:
      - "$API_PORT:3000"