version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./:/app
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      ACCESS_KEY_ID: $ACCESS_KEY_ID
      SECRET_ACCESS_KEY: $SECRET_ACCESS_KEY
      API_DOMAIN: $DEV_HOST:$FRONT_PORT
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
    ports:
      - "$API_PORT:3000"

  db:
    image: postgres:16.0-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./tmp/db:/var/lib/postgresql/data_1"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data